language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
before_script:
  - pip install -r requirements.txt
script:
  - flake8 .
  - isort --recursive --diff . && isort --recursive --check-only .
  - py.test
